FROM golang:1.13.8 AS builder
WORKDIR /go/src/github.com/kubevirt/hyperconverged-cluster-operator/
COPY . .
RUN find /tmp -exec ls -l {} \;
RUN find /var -exec ls -l {} \;
RUN cd tools/csv-merger && go build && cd ../manifest-templator && go build

FROM quay.io/openshift/origin-operator-registry:latest
COPY --from=builder /go/src/github.com/kubevirt/hyperconverged-cluster-operator /hyperconverged-cluster-operator
USER root
RUN find /tmp -exec ls -l {} \;
RUN find /var -exec ls -l {} \;

ENTRYPOINT ["/hyperconverged-cluster-operator/hack/nightly-registry.sh"]
